const STORAGE_KEY='family-office-nunez-v2';
const state=loadState();
let pendingImport=null;
let confirmAction=null;

const $=s=>document.querySelector(s);
const $$=s=>[...document.querySelectorAll(s)];
const eur=new Intl.NumberFormat('es-ES',{style:'currency',currency:'EUR',maximumFractionDigits:2});
const num=new Intl.NumberFormat('es-ES',{maximumFractionDigits:2});
const pct=new Intl.NumberFormat('es-ES',{style:'percent',minimumFractionDigits:2,maximumFractionDigits:2});

function defaultState(){return{portfolio:[],history:[],lastImport:null,theme:'light'}}
function loadState(){try{return{...defaultState(),...JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}')}}catch{return defaultState()}}
function saveState(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function parseLocaleNumber(v){if(v===null||v===undefined||v==='')return 0;return Number(String(v).trim().replace(/\./g,'').replace(',','.'))||0}
function dateEs(v){if(!v)return '—';const d=new Date(v+'T12:00:00');return Number.isNaN(d.valueOf())?'—':new Intl.DateTimeFormat('es-ES').format(d)}
function escapeHtml(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function totals(list=state.portfolio){const value=list.reduce((a,p)=>a+p.value,0),cost=list.reduce((a,p)=>a+p.buyinTotal,0),dividends=list.reduce((a,p)=>a+p.totalDividendRate,0);return{value,cost,dividends,gain:value-cost,yield:value?dividends/value:0,yoc:cost?dividends/cost:0,count:list.length}}
function normalize(row){return{symbol:row.symbol||'',isin:row.isin||'',name:row.name||row.symbol||'Sin nombre',quantity:parseLocaleNumber(row.quantity),buyin:parseLocaleNumber(row.buyin),buyinTotal:parseLocaleNumber(row.buyinTotal),price:parseLocaleNumber(row.price),value:parseLocaleNumber(row.value),gain:parseLocaleNumber(row.gain),gainRel:parseLocaleNumber(row.gainRel),currency:row.currency||'EUR',allocation:parseLocaleNumber(row.allocation),dividendYield:parseLocaleNumber(row.dividendYield),dividendYieldOnBuyin:parseLocaleNumber(row.dividendYieldOnBuyin),totalDividendRate:parseLocaleNumber(row.totalDividendRate),dividendRate:parseLocaleNumber(row.dividendRate),dividendFrequency:row.dividendFrequency||'',dividendCagr:parseLocaleNumber(row.dividendCagr),sector:row.sector||'Sin clasificar',country:row.country||'Sin país',originalDividendCurrency:row.originalDividendCurrency||'',transactions:parseLocaleNumber(row.transactions),exDate:row.exDate||'',payDate:row.payDate||'',note:row.note||'',taxRate:parseLocaleNumber(row.taxRate)}}
function keyOf(p){return p.isin||`${p.symbol}|${p.name}`}

function render(){applyTheme();renderDashboard();renderPortfolio();renderHistory();renderFilters()}
function applyTheme(){document.body.classList.toggle('dark',state.theme==='dark');$('#themeBtn wa-icon')?.setAttribute('name',state.theme==='dark'?'sun':'moon')}
function renderDashboard(){const t=totals();$('#kpiValue').textContent=eur.format(t.value);$('#kpiPositions').textContent=`${t.count} posiciones`;$('#kpiCost').textContent=eur.format(t.cost);$('#kpiGain').textContent=`Plusvalía: ${eur.format(t.gain)}`;$('#kpiDividends').textContent=eur.format(t.dividends);$('#kpiYield').textContent=`Yield: ${pct.format(t.yield)}`;$('#kpiYoc').textContent=pct.format(t.yoc);$('#kpiMonthly').textContent=`Media mensual: ${eur.format(t.dividends/12)}`;$('#lastUpdated').textContent=state.lastImport?`Última importación: ${new Intl.DateTimeFormat('es-ES',{dateStyle:'long',timeStyle:'short'}).format(new Date(state.lastImport))}`:'Importa el CSV de DivvyDiary para comenzar.';renderBars('#sectorChart',groupBy('sector'));renderBars('#countryChart',groupBy('country'));const top=[...state.portfolio].sort((a,b)=>b.value-a.value).slice(0,7);$('#topPositions').innerHTML=top.length?top.map(p=>`<tr><td class="company-cell"><strong>${escapeHtml(p.name)}</strong><small>${escapeHtml(p.symbol)} · ${escapeHtml(p.isin)}</small></td><td>${eur.format(p.value)}</td><td>${pct.format(p.allocation||p.value/(t.value||1))}</td><td>${eur.format(p.totalDividendRate)}</td><td>${pct.format(p.dividendYield)}</td></tr>`).join(''):'<tr><td colspan="5" class="empty-cell">Todavía no hay posiciones.</td></tr>'}
function groupBy(field){const map={};for(const p of state.portfolio)map[p[field]||'Sin clasificar']=(map[p[field]||'Sin clasificar']||0)+p.value;return Object.entries(map).sort((a,b)=>b[1]-a[1]).slice(0,8)}
function renderBars(selector,data){const el=$(selector);if(!data.length){el.className='bar-chart empty-state';el.textContent='Sin datos';return}const max=data[0][1]||1;el.className='bar-chart';el.innerHTML=data.map(([name,value])=>`<div class="bar-row"><span title="${escapeHtml(name)}">${escapeHtml(name)}</span><div class="bar-track"><div class="bar-fill" style="width:${Math.max(2,value/max*100)}%"></div></div><span class="bar-value">${pct.format(value/totals().value)}</span></div>`).join('')}
function renderPortfolio(){const q=($('#searchInput')?.value||'').toLowerCase(),sector=$('#sectorFilter')?.value||'',country=$('#countryFilter')?.value||'';const list=state.portfolio.filter(p=>(!q||`${p.name} ${p.symbol} ${p.isin}`.toLowerCase().includes(q))&&(!sector||p.sector===sector)&&(!country||p.country===country)).sort((a,b)=>b.value-a.value);$('#portfolioRows').innerHTML=list.length?list.map(p=>`<tr><td class="company-cell"><strong>${escapeHtml(p.name)}</strong><small>${escapeHtml(p.symbol)} · ${escapeHtml(p.isin)}</small></td><td>${num.format(p.quantity)}</td><td>${eur.format(p.buyin)}</td><td>${eur.format(p.price)}</td><td>${eur.format(p.value)}</td><td class="${p.gain>=0?'positive':'negative'}">${eur.format(p.gain)}<br><small>${pct.format(p.gainRel)}</small></td><td>${pct.format(p.allocation)}</td><td>${eur.format(p.totalDividendRate)}</td><td>${pct.format(p.dividendYield)}</td><td>${pct.format(p.dividendYieldOnBuyin)}</td><td>${dateEs(p.payDate)}</td></tr>`).join(''):'<tr><td colspan="11" class="empty-cell">No hay resultados.</td></tr>'}
function renderFilters(){for(const [id,field,label] of [['#sectorFilter','sector','Todos'],['#countryFilter','country','Todos']]){const el=$(id),current=el.value,values=[...new Set(state.portfolio.map(p=>p[field]).filter(Boolean))].sort();el.innerHTML=`<wa-option value="">${label}</wa-option>`+values.map(v=>`<wa-option value="${escapeHtml(v)}">${escapeHtml(v)}</wa-option>`).join('');el.value=values.includes(current)?current:''}}
function renderHistory(){const rows=[...state.history].sort((a,b)=>new Date(b.date)-new Date(a.date));$('#historyRows').innerHTML=rows.length?rows.map(h=>`<tr><td>${new Intl.DateTimeFormat('es-ES',{dateStyle:'medium'}).format(new Date(h.date))}</td><td>${eur.format(h.value)}</td><td>${eur.format(h.cost)}</td><td class="${h.gain>=0?'positive':'negative'}">${eur.format(h.gain)}</td><td>${eur.format(h.dividends)}</td><td>${h.count}</td><td><wa-button size="small" appearance="plain" data-delete-snapshot="${h.id}"><wa-icon name="trash"></wa-icon></wa-button></td></tr>`).join(''):'<tr><td colspan="7" class="empty-cell">No hay cierres guardados.</td></tr>';const chronological=[...state.history].sort((a,b)=>new Date(a.date)-new Date(b.date));const chart=$('#historyChart');if(!chronological.length){chart.className='history-chart empty-state';chart.textContent='Sin cierres mensuales';return}const max=Math.max(...chronological.map(h=>h.value),1);chart.className='history-chart';chart.innerHTML=`<div class="history-bars">${chronological.map(h=>`<div class="history-col"><div class="history-bar" style="height:${Math.max(3,h.value/max*100)}%" data-value="${eur.format(h.value)}"></div><small>${new Intl.DateTimeFormat('es-ES',{month:'short',year:'2-digit'}).format(new Date(h.date))}</small></div>`).join('')}</div>`}
function showNotice(msg){const n=$('#notice');n.textContent=msg;n.classList.add('show');clearTimeout(n._timer);n._timer=setTimeout(()=>n.classList.remove('show'),3000)}
function switchView(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===id));scrollTo({top:0,behavior:'smooth'})}
function openImport(){pendingImport=null;$('#importStepSelect').hidden=false;$('#importStepPreview').hidden=true;$('#confirmImportBtn').hidden=true;$('#importDialog').open=true}
function parseCsv(file){if(!window.Papa){showNotice('No se ha cargado el lector CSV. Comprueba la conexión.');return}Papa.parse(file,{header:true,skipEmptyLines:true,delimiter:';',encoding:'UTF-8',complete:r=>{const required=['isin','name','quantity','value'];const missing=required.filter(k=>!r.meta.fields?.includes(k));if(missing.length){showNotice(`CSV no reconocido. Faltan: ${missing.join(', ')}`);return}const list=r.data.map(normalize).filter(p=>p.isin||p.symbol);if(!list.length){showNotice('El CSV no contiene posiciones válidas.');return}pendingImport={file,list};previewImport()},error:e=>showNotice(`Error al leer el CSV: ${e.message}`)})}
function previewImport(){const old=new Map(state.portfolio.map(p=>[keyOf(p),p])),fresh=new Map(pendingImport.list.map(p=>[keyOf(p),p]));let added=0,updated=0,removed=0;for(const k of fresh.keys())old.has(k)?updated++:added++;for(const k of old.keys())if(!fresh.has(k))removed++;const t=totals(pendingImport.list);$('#importFilename').textContent=pendingImport.file.name;$('#importSummary').textContent='Archivo reconocido correctamente.';$('#previewCount').textContent=t.count;$('#previewValue').textContent=eur.format(t.value);$('#previewDividends').textContent=eur.format(t.dividends);$('#previewNew').textContent=`${added} nuevas`;$('#previewUpdated').textContent=`${updated} actualizadas`;$('#previewRemoved').textContent=`${removed} ausentes`;$('#importStepSelect').hidden=true;$('#importStepPreview').hidden=false;$('#confirmImportBtn').hidden=false}
function confirmImport(){if(!pendingImport)return;const mode=$('#importMode').value||'update';if(mode==='replace')state.portfolio=pendingImport.list;else{const map=new Map(state.portfolio.map(p=>[keyOf(p),p]));for(const p of pendingImport.list){const old=map.get(keyOf(p));map.set(keyOf(p),{...old,...p,note:p.note||old?.note||''})}state.portfolio=[...map.values()]}state.lastImport=new Date().toISOString();saveState();render();$('#importDialog').open=false;showNotice(`${pendingImport.list.length} posiciones importadas correctamente.`);pendingImport=null}
function saveSnapshot(){if(!state.portfolio.length){showNotice('Importa primero una cartera.');return}const t=totals(),month=new Date().toISOString().slice(0,7);const existing=state.history.findIndex(h=>h.month===month);const snap={id:crypto.randomUUID?.()||String(Date.now()),month,date:new Date().toISOString(),...t};if(existing>=0){snap.id=state.history[existing].id;state.history[existing]=snap}else state.history.push(snap);saveState();renderHistory();showNotice('Cierre mensual guardado.')}
function download(name,content,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function exportJson(){download(`family-office-backup-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify(state,null,2),'application/json')}
function restoreJson(file){const reader=new FileReader();reader.onload=()=>{try{const data=JSON.parse(reader.result);if(!Array.isArray(data.portfolio)||!Array.isArray(data.history))throw Error('Formato no válido');Object.assign(state,defaultState(),data);saveState();render();showNotice('Copia restaurada correctamente.')}catch(e){showNotice(`No se pudo restaurar: ${e.message}`)}};reader.readAsText(file)}
function markdown(){const t=totals(),sector=groupAll('sector'),country=groupAll('country');const lines=[`# Informe Family Office Núñez`,``,`Fecha: ${new Intl.DateTimeFormat('es-ES',{dateStyle:'long'}).format(new Date())}`,``,`## Resumen`,`- Valor de cartera: ${eur.format(t.value)}`,`- Coste invertido: ${eur.format(t.cost)}`,`- Plusvalía: ${eur.format(t.gain)}`,`- Dividendos anuales estimados: ${eur.format(t.dividends)}`,`- Yield actual: ${pct.format(t.yield)}`,`- Yield on cost: ${pct.format(t.yoc)}`,`- Número de posiciones: ${t.count}`,``,`## Posiciones`,`| Empresa | Ticker | ISIN | Valor | Peso | Dividendo anual | Yield | YOC |`,`|---|---|---|---:|---:|---:|---:|---:|`,...state.portfolio.sort((a,b)=>b.value-a.value).map(p=>`| ${p.name.replaceAll('|','/')} | ${p.symbol} | ${p.isin} | ${eur.format(p.value)} | ${pct.format(p.allocation)} | ${eur.format(p.totalDividendRate)} | ${pct.format(p.dividendYield)} | ${pct.format(p.dividendYieldOnBuyin)} |`),``,`## Distribución por sector`,...sector.map(([k,v])=>`- ${k}: ${pct.format(v/t.value)}`),``,`## Distribución por país`,...country.map(([k,v])=>`- ${k}: ${pct.format(v/t.value)}`),``,`## Solicitud de análisis`,`Analiza la diversificación, la sostenibilidad del dividendo, las concentraciones, los riesgos y las prioridades para nuevas aportaciones. Distingue entre observaciones objetivas y recomendaciones.`];download(`informe-family-office-${new Date().toISOString().slice(0,10)}.md`,lines.join('\n'),'text/markdown')}
function groupAll(field){const m={};state.portfolio.forEach(p=>m[p[field]||'Sin clasificar']=(m[p[field]||'Sin clasificar']||0)+p.value);return Object.entries(m).sort((a,b)=>b[1]-a[1])}
function askConfirm(text,action){$('#confirmText').textContent=text;confirmAction=action;$('#confirmDialog').open=true}

$$('.nav-item').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.view)));
$$('[data-go]').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.go)));
['#importBtn','#portfolioImportBtn'].forEach(s=>$(s).addEventListener('click',openImport));
$('#chooseCsvBtn').addEventListener('click',()=>$('#csvFile').click());$('#csvFile').addEventListener('change',e=>e.target.files[0]&&parseCsv(e.target.files[0]));
$('#dropZone').addEventListener('dragover',e=>{e.preventDefault();e.currentTarget.classList.add('dragover')});$('#dropZone').addEventListener('dragleave',e=>e.currentTarget.classList.remove('dragover'));$('#dropZone').addEventListener('drop',e=>{e.preventDefault();e.currentTarget.classList.remove('dragover');e.dataTransfer.files[0]&&parseCsv(e.dataTransfer.files[0])});
$('#cancelImportBtn').addEventListener('click',()=>$('#importDialog').open=false);$('#confirmImportBtn').addEventListener('click',confirmImport);
$('#searchInput').addEventListener('input',renderPortfolio);$('#sectorFilter').addEventListener('change',renderPortfolio);$('#countryFilter').addEventListener('change',renderPortfolio);
['#snapshotBtn','#historySnapshotBtn'].forEach(s=>$(s).addEventListener('click',saveSnapshot));
$('#exportJsonBtn').addEventListener('click',exportJson);$('#restoreJsonBtn').addEventListener('click',()=>$('#jsonFile').click());$('#jsonFile').addEventListener('change',e=>e.target.files[0]&&restoreJson(e.target.files[0]));$('#markdownBtn').addEventListener('click',markdown);
$('#clearBtn').addEventListener('click',()=>askConfirm('Se borrarán la cartera y todos los cierres guardados en este navegador.',()=>{Object.assign(state,defaultState());saveState();render();showNotice('Datos locales eliminados.')}));
$('#confirmCancel').addEventListener('click',()=>$('#confirmDialog').open=false);$('#confirmOk').addEventListener('click',()=>{confirmAction?.();confirmAction=null;$('#confirmDialog').open=false});
$('#themeBtn').addEventListener('click',()=>{state.theme=state.theme==='dark'?'light':'dark';saveState();applyTheme()});
document.addEventListener('click',e=>{const btn=e.target.closest('[data-delete-snapshot]');if(btn)askConfirm('¿Quieres eliminar este cierre mensual?',()=>{state.history=state.history.filter(h=>h.id!==btn.dataset.deleteSnapshot);saveState();renderHistory();showNotice('Cierre eliminado.')})});
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
render();
